# Generated by Django 3.1 on 2020-08-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mappings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchReference', models.TextField()),
                ('transactionReference', models.TextField()),
                ('buyerName', models.TextField()),
                ('supplierName', models.TextField()),
                ('invoiceReference', models.TextField()),
                ('poReference', models.TextField()),
                ('invoiceDate', models.TextField()),
                ('invoiceAmount', models.TextField()),
                ('invoiceCurrency', models.TextField()),
                ('maturityDate', models.TextField()),
                ('paymentDate', models.TextField()),
                ('tenor', models.TextField()),
                ('netAmount', models.TextField()),
                ('grossAmount', models.TextField()),
                ('discountAmount', models.TextField()),
                ('adjustmentAmount', models.TextField()),
                ('adjustmentReasonCode', models.TextField()),
                ('paymentTerm', models.TextField()),
                ('status', models.TextField()),
                ('notes', models.TextField()),
            ],
        ),
    ]
